### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by phls** [jaalto/project--perl-ddir#1]
Hi,

I intend to adopt ddir package in Debian e update it. Could you release a new version?

There is a bug reported with a solution that maybe you can use it:

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=903093

Best regards,

**Comment by jaalto** [comment]
Hi, This Debian bug is fixed in latest HEAD. You can package directly from Git. See the tags for release information. There has never been separate release archives as they are unnecessary with modern Git.,
